import { TConditionId } from "../entities/global";

type Conditions = Record<TConditionId, string>;

export const conditions: Conditions = {
  "achilles-rupture": "Achilles rupture",
  "achilles-tendinopathy": "Achilles tendinopathy",
  "acromioclavicular-joint-injury": "Acromioclavicular joint injury",
  "adductor-strain": "Adductor strain",
  "adductor-tendon-rupture": "Adductor tendon rupture",
  "adductor-tendinopathy": "Adductor tendinopathy",
  "adhesive-capsulitis": "Adhesive capsulitis",
  "ankle-fracture": "Ankle fracture",
  "ankle-impingement": "Ankle impingement",
  "ankle-osteoarthritis": "Ankle osteoarthritis",
  "ankle-sprain": "Ankle sprain",
  "ankylosing-spondylitis": "Ankylosing spondylitis",
  "anterior-cruciate-ligament-injury": "Anterior cruciate ligament injury",
  "bankart-repair": "Bankart repair",
  "biceps-tendinopathy": "Biceps tendinopathy",
  "biceps-tendon-rupture": "Biceps tendon rupture",
  "bone-stress-injury": "Bone stress injury",
  bursitis: "Bursitis",
  "calcaneal-apophysitis": "Calcaneal apophysitis",
  "calcaneal-spurs": "Calcaneal spurs",
  "calf-muscle-strain": "Calf muscle strain",
  "carpal-tunnel-syndrome": "Carpal tunnel syndrome",
  "cervical-radiculopathy": "Cervical radiculopathy",
  "chondromalacia-patellae": "Chondromalacia patellae",
  "chronic-ankle-instability": "Chronic ankle instability",
  "clavicle-fracture": "Clavicle fracture",
  coccydynia: "Coccydynia",
  "coccyx-fracture": "Coccyx fracture",
  "compression-fracture": "Compression fracture",
  "dead-arm-syndrome": "Dead arm syndrome",
  "degenerative-disc-disease": "Degenerative disc disease",
  "disk-herniation": "Disk herniation",
  "elbow-osteoarthritis": "Elbow osteoarthritis",
  "facet-joint-syndrome": "Facet joint syndrome",
  "fat-pad-syndrome": "Fat pad syndrome",
  "femoral-fracture": "Femoral fracture",
  fibromyalgia: "Fibromyalgia",
  "gluteal-strain": "Gluteal strain",
  "gluteal-tendinopathy": "Gluteal tendinopathy",
  "greater-trochanteric-pain-syndrome": "Greater trochanteric pain syndrome",
  "haglunds-deformity": "Haglund's deformity",
  "hamstring-strain": "Hamstring strain",
  "hamstring-tendinopathy": "Hamstring tendinopathy",
  "hamstring-tendon-tear": "Hamstring tendon tear",
  "hand-osteoarthritis": "Hand osteoarthritis",
  hernia: "Hernia",
  "hip-arthroscopy": "Hip arthroscopy",
  "hip-fracture": "Hip fracture",
  "hip-impingement": "Hip impingement",
  "hip-labral-tear": "Hip labral tear",
  "hip-osteoarthritis": "Hip osteoarthritis",
  "hip-replacement": "Hip replacement",
  "iliopsoas-strain": "Iliopsoas strain",
  "iliopsoas-tendinopathy": "Iliopsoas tendinopathy",
  "iliotibial-band-syndrome": "Iliotibial band syndrome",
  "knee-arthroscopy": "Knee arthroscopy",
  "knee-osteoarthritis": "Knee osteoarthritis",
  "knee-replacement": "Knee replacement",
  "lateral-ankle-sprain": "Lateral ankle sprain",
  "lateral-collateral-ligament-injury": "Lateral collateral ligament injury",
  "lateral-epicondylitis": "Lateral epicondylitis",
  "lisfranc-injury": "Lisfranc injury",
  "lower-back-pain": "Lower back pain",
  "medial-ankle-sprain": "Medial ankle sprain",
  "medial-collateral-ligament-injury": "Medial collateral ligament injury",
  "medial-epicondylitis": "Medial epicondylitis",
  "medial-tibial-stress-syndrome": "Medial tibial stress syndrome",
  "meniscus-tear": "Meniscus tear",
  "metatarsal-fracture": "Metatarsal fracture",
  "mortons-neuroma": "Morton's neuroma",
  "neck-pain": "Neck pain",
  "osgood-schlatter-disease": "Osgood-Schlatter disease",
  osteoporosis: "Osteoporosis",
  "osteochondritis-dissecans": "Osteochondritis dissecans",
  "patellar-dislocation": "Patellar dislocation",
  "patellar-fracture": "Patellar fracture",
  "patellar-tendinopathy": "Patellar tendinopathy",
  "patellofemoral-pain-syndrome": "Patellofemoral pain syndrome",
  "pectoralis-major-strain": "Pectoralis major strain",
  "pectoralis-major-tendon-rupture": "Pectoralis major tendon rupture",
  "pelvic-floor-dysfunction": "Pelvic floor dysfunction",
  "pelvic-pain": "Pelvic pain",
  "piriformis-syndrome": "Piriformis syndrome",
  "plantar-fasciitis": "Plantar fasciitis",
  "plantar-heel-pain": "Plantar heel pain",
  "posterior-cruciate-ligament-injury": "Posterior cruciate ligament injury",
  "psoriatic-arthritis": "Psoriatic arthritis",
  "quadriceps-contusion": "Quadriceps contusion",
  "quadriceps-strain": "Quadriceps strain",
  "quadriceps-tendon-tear": "Quadriceps tendon tear",
  "rheumatoid-arthritis": "Rheumatoid arthritis",
  "rotator-cuff-tear": "Rotator cuff tear",
  "rotator-cuff-tendinopathy": "Rotator cuff tendinopathy",
  "sacroiliac-joint-syndrome": "Sacroiliac joint syndrome",
  sciatica: "Sciatica",
  scoliosis: "Scoliosis",
  "shoulder-dislocation": "Shoulder dislocation",
  "shoulder-impingement": "Shoulder impingement",
  "shoulder-instability": "Shoulder instability",
  "shoulder-osteoarthritis": "Shoulder osteoarthritis",
  "shoulder-subluxation": "Shoulder subluxation",
  "spinal-stenosis": "Spinal stenosis",
  spondylolisthesis: "Spondylolisthesis",
  spondylosis: "Spondylosis",
  "sports-hernia": "Sports hernia",
  "stress-fracture": "Stress fracture",
  "subacromial-decompression": "Subacromial decompression",
  "subacromial-shoulder-pain": "Subacromial shoulder pain",
  "syndesmotic-ankle-sprain": "Syndesmotic ankle sprain",
  "tarsal-tunnel-syndrome": "Tarsal tunnel syndrome",
  "thoracic-outlet-syndrome": "Thoracic outlet syndrome",
  "triceps-tendinopathy": "Triceps tendinopathy",
  "turf-toe": "Turf toe",
  "upper-back-pain": "Upper back pain",
  "whiplash-associated-disorders": "Whiplash associated disorders",
  "wrist-fracture": "Wrist fracture",
  "wrist-sprain": "Wrist sprain",
};

export const conditionOptions = Object.entries(conditions).map(
  ([value, label]) => ({
    value: value as TConditionId,
    label,
  })
);

export const conditionIdEnum = Object.keys(conditions) as [
  keyof typeof conditions,
];
