export enum Collection {
  Clients = "clients",
  Programs = "programs",
  Clinicians = "clinicians",
  Clinics = "clinics",
  Versions = "versions",
  Days = "days",
  Phases = "phases",
  Invitations = "invitations",
  Exercises = "exercises",
  Videos = "videos",
}

export type TConditionId =
  | "achilles-rupture"
  | "achilles-tendinopathy"
  | "acromioclavicular-joint-injury"
  | "adductor-strain"
  | "adductor-tendon-rupture"
  | "adductor-tendinopathy"
  | "adhesive-capsulitis"
  | "ankle-fracture"
  | "ankle-impingement"
  | "ankle-osteoarthritis"
  | "ankle-sprain"
  | "ankylosing-spondylitis"
  | "anterior-cruciate-ligament-injury"
  | "bankart-repair"
  | "biceps-tendinopathy"
  | "biceps-tendon-rupture"
  | "bone-stress-injury"
  | "bursitis"
  | "calcaneal-apophysitis"
  | "calcaneal-spurs"
  | "calf-muscle-strain"
  | "carpal-tunnel-syndrome"
  | "cervical-radiculopathy"
  | "chondromalacia-patellae"
  | "chronic-ankle-instability"
  | "clavicle-fracture"
  | "coccydynia"
  | "coccyx-fracture"
  | "compression-fracture"
  | "dead-arm-syndrome"
  | "degenerative-disc-disease"
  | "disk-herniation"
  | "elbow-osteoarthritis"
  | "facet-joint-syndrome"
  | "fat-pad-syndrome"
  | "femoral-fracture"
  | "fibromyalgia"
  | "gluteal-strain"
  | "gluteal-tendinopathy"
  | "greater-trochanteric-pain-syndrome"
  | "haglunds-deformity"
  | "hamstring-strain"
  | "hamstring-tendinopathy"
  | "hamstring-tendon-tear"
  | "hand-osteoarthritis"
  | "hernia"
  | "hip-arthroscopy"
  | "hip-fracture"
  | "hip-impingement"
  | "hip-labral-tear"
  | "hip-osteoarthritis"
  | "hip-replacement"
  | "iliopsoas-strain"
  | "iliopsoas-tendinopathy"
  | "iliotibial-band-syndrome"
  | "knee-arthroscopy"
  | "knee-osteoarthritis"
  | "knee-replacement"
  | "lateral-ankle-sprain"
  | "lateral-collateral-ligament-injury"
  | "lateral-epicondylitis"
  | "lisfranc-injury"
  | "lower-back-pain"
  | "medial-ankle-sprain"
  | "medial-collateral-ligament-injury"
  | "medial-epicondylitis"
  | "medial-tibial-stress-syndrome"
  | "meniscus-tear"
  | "metatarsal-fracture"
  | "mortons-neuroma"
  | "neck-pain"
  | "osgood-schlatter-disease"
  | "osteoporosis"
  | "osteochondritis-dissecans"
  | "patellar-dislocation"
  | "patellar-fracture"
  | "patellar-tendinopathy"
  | "patellofemoral-pain-syndrome"
  | "pectoralis-major-strain"
  | "pectoralis-major-tendon-rupture"
  | "pelvic-floor-dysfunction"
  | "pelvic-pain"
  | "piriformis-syndrome"
  | "plantar-fasciitis"
  | "plantar-heel-pain"
  | "posterior-cruciate-ligament-injury"
  | "psoriatic-arthritis"
  | "quadriceps-contusion"
  | "quadriceps-strain"
  | "quadriceps-tendon-tear"
  | "rheumatoid-arthritis"
  | "rotator-cuff-repair"
  | "rotator-cuff-tear"
  | "rotator-cuff-tendinopathy"
  | "sacroiliac-joint-syndrome"
  | "sciatica"
  | "scoliosis"
  | "shoulder-dislocation"
  | "shoulder-impingement"
  | "shoulder-instability"
  | "shoulder-osteoarthritis"
  | "shoulder-subluxation"
  | "spinal-stenosis"
  | "spondylolisthesis"
  | "spondylosis"
  | "sports-hernia"
  | "stress-fracture"
  | "subacromial-decompression"
  | "subacromial-shoulder-pain"
  | "syndesmotic-ankle-sprain"
  | "tarsal-tunnel-syndrome"
  | "thoracic-outlet-syndrome"
  | "triceps-tendinopathy"
  | "turf-toe"
  | "upper-back-pain"
  | "whiplash-associated-disorders"
  | "wrist-fracture"
  | "wrist-sprain";

export type TEuneoProgramId =
  | "achilles-tendinopathy"
  | "hip-replacement"
  | "knee-replacement"
  | "lateral-ankle-sprain"
  | "meniscus-tear"
  | "osgood-schlatter-disease"
  | "patellofemoral-pain-syndrome"
  | "plantar-fasciitis"
  | "plantar-heel-pain"
  | "severs-disease";
