export enum Collection {
  Clients = "clients",
  Programs = "programs",
  Clinicians = "clinicians",
  Versions = "versions",
  Days = "days",
  Phases = "phases",
  Invitations = "invitations",
  Exercises = "exercises",
}

export type TConditionId =
  | "achilles-rupture"
  | "achilles-tendinopathy"
  | "adductor-strain"
  | "adductor-tendon-rupture"
  | "adductor-tendinopathy"
  | "ankle-fracture"
  | "ankle-impingement"
  | "ankle-osteoarthritis"
  | "ankle-sprain"
  | "anterior-cruciate-ligament-injury"
  | "bursitis"
  | "calf-muscle-strain"
  | "heel-spurs"
  | "chondromalacia-patella"
  | "chronic-ankle-instability"
  | "fat-pad-syndrome"
  | "femoral-fracture"
  | "greater-trochanteric-pain-syndrome"
  | "gluteal-tendinopathy"
  | "gluteal-strain"
  | "hamstring-strain"
  | "hamstring-tendon-tear"
  | "hamstring-tendinopathy"
  | "hernia"
  | "hip-fracture"
  | "hip-impingement"
  | "hip-osteoarthritis"
  | "hip-replacement"
  | "iliotibial-band-syndrome"
  | "iliopsoas-tendinopathy"
  | "iliopsoas-strain"
  | "labral-tear"
  | "lateral-collateral-ligament-injury"
  | "lisfranc-injury"
  | "lower-back-pain"
  | "medial-collateral-ligament-injury"
  | "meniscus-tear"
  | "metatarsal-fracture"
  | "mortons-neuroma"
  | "osgood-schlatter-disease"
  | "osteoporosis"
  | "osteochondritis-dissecans"
  | "patellar-dislocation"
  | "patellar-fracture"
  | "patellar-tendinopathy"
  | "patellofemoral-pain-syndrome"
  | "peroneal-tendinopathy"
  | "piriformis-syndrome"
  | "plantar-fasciitis"
  | "plantar-heel-pain"
  | "popliteus-strain"
  | "popliteus-tendinopathy"
  | "posterior-cruciate-ligament-injury"
  | "quadriceps-contusion"
  | "quadriceps-strain"
  | "quadriceps-tendon-tear"
  | "sciatica"
  | "severs-disease"
  | "shin-splints"
  | "stress-fracture"
  | "sports-hernia"
  | "tarsal-tunnel-syndrome"
  | "turf-toe"
  | "knee-replacement";

export type TEuneoProgramId =
  | "achilles-tendinopathy"
  | "hip-replacement"
  | "knee-replacement"
  | "lateral-ankle-sprain"
  | "meniscus-tear"
  | "osgood-schlatter-disease"
  | "patellofemoral-pain-syndrome"
  | "plantar-fasciitis"
  | "plantar-heel-pain"
  | "severs-disease";
